---
- hosts: all
  become: true
  tasks:
    - name: install ntp
      apt:
        pkg: ntp
        state: present
      notify:
        - run update
    - name: install vim
      apt:
        pkg: vim
        state: present
    - name: start ntp service
      service:
        name: ntp
        state: started
        enable: true
  handlers:
    - name: run update
      apt:
        update_cache: yes
